#
# Copyright (c) 2026, RTE (http://www.rte-france.com)
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
PREFIX cim:  <%%CIM_NS%%>

PREFIX md:   <http://iec.ch/TC57/61970-552/ModelDescription/1#>

SELECT * WHERE {
  ?id rdf:type cim:ExcPIC .
  OPTIONAL { ?id cim:ExcitationSystemDynamics.SynchronousMachineDynamics ?synchronousMachineId . }
  OPTIONAL { ?id cim:ExcPIC.e1 ?e1 . }
  OPTIONAL { ?id cim:ExcPIC.e2 ?e2 . }
  OPTIONAL { ?id cim:ExcPIC.efdmax ?efdmax . }
  OPTIONAL { ?id cim:ExcPIC.efdmin ?efdmin . }
  OPTIONAL { ?id cim:ExcPIC.ka ?ka . }
  OPTIONAL { ?id cim:ExcPIC.kc ?kc . }
  OPTIONAL { ?id cim:ExcPIC.ke ?ke . }
  OPTIONAL { ?id cim:ExcPIC.kf ?kf . }
  OPTIONAL { ?id cim:ExcPIC.ki ?ki . }
  OPTIONAL { ?id cim:ExcPIC.kp ?kp . }
  OPTIONAL { ?id cim:ExcPIC.se1 ?se1 . }
  OPTIONAL { ?id cim:ExcPIC.se2 ?se2 . }
  OPTIONAL { ?id cim:ExcPIC.ta1 ?ta1 . }
  OPTIONAL { ?id cim:ExcPIC.ta2 ?ta2 . }
  OPTIONAL { ?id cim:ExcPIC.ta3 ?ta3 . }
  OPTIONAL { ?id cim:ExcPIC.ta4 ?ta4 . }
  OPTIONAL { ?id cim:ExcPIC.te ?te . }
  OPTIONAL { ?id cim:ExcPIC.tf1 ?tf1 . }
  OPTIONAL { ?id cim:ExcPIC.tf2 ?tf2 . }
  OPTIONAL { ?id cim:ExcPIC.vr1 ?vr1 . }
  OPTIONAL { ?id cim:ExcPIC.vr2 ?vr2 . }
  OPTIONAL { ?id cim:ExcPIC.vrmax ?vrmax . }
  OPTIONAL { ?id cim:ExcPIC.vrmin ?vrmin . }
}
