#
# Copyright (c) 2026, RTE (http://www.rte-france.com)
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
PREFIX cim:  <%%CIM_NS%%>

PREFIX md:   <http://iec.ch/TC57/61970-552/ModelDescription/1#>

SELECT * WHERE {
  ?id rdf:type cim:ExcST3A .
  OPTIONAL { ?id cim:ExcitationSystemDynamics.SynchronousMachineDynamics ?synchronousMachineId . }
  OPTIONAL { ?id cim:ExcST3A.efdmax ?efdmax . }
  OPTIONAL { ?id cim:ExcST3A.kc ?kc . }
  OPTIONAL { ?id cim:ExcST3A.kg ?kg . }
  OPTIONAL { ?id cim:ExcST3A.ki ?ki . }
  OPTIONAL { ?id cim:ExcST3A.kj ?kj . }
  OPTIONAL { ?id cim:ExcST3A.km ?km . }
  OPTIONAL { ?id cim:ExcST3A.kp ?kp . }
  OPTIONAL { ?id cim:ExcST3A.ks ?ks . }
  OPTIONAL { ?id cim:ExcST3A.ks1 ?ks1 . }
  OPTIONAL { ?id cim:ExcST3A.tb ?tb . }
  OPTIONAL { ?id cim:ExcST3A.tc ?tc . }
  OPTIONAL { ?id cim:ExcST3A.thetap ?thetap . }
  OPTIONAL { ?id cim:ExcST3A.tm ?tm . }
  OPTIONAL { ?id cim:ExcST3A.vbmax ?vbmax . }
  OPTIONAL { ?id cim:ExcST3A.vgmax ?vgmax . }
  OPTIONAL { ?id cim:ExcST3A.vimax ?vimax . }
  OPTIONAL { ?id cim:ExcST3A.vimin ?vimin . }
  OPTIONAL { ?id cim:ExcST3A.vrmax ?vrmax . }
  OPTIONAL { ?id cim:ExcST3A.vrmin ?vrmin . }
  OPTIONAL { ?id cim:ExcST3A.xl ?xl . }
}
