#
# Copyright (c) 2026, RTE (http://www.rte-france.com)
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
PREFIX cim:  <%%CIM_NS%%>

PREFIX md:   <http://iec.ch/TC57/61970-552/ModelDescription/1#>

SELECT * WHERE {
  ?id rdf:type cim:GovSteamFV3 .
  OPTIONAL { ?id cim:TurbineGovernorDynamics.SynchronousMachineDynamics ?synchronousMachineId  . }
  OPTIONAL { ?id cim:GovSteamFV3.k ?k . }
  OPTIONAL { ?id cim:GovSteamFV3.k1 ?k1 . }
  OPTIONAL { ?id cim:GovSteamFV3.k2 ?k2 . }
  OPTIONAL { ?id cim:GovSteamFV3.k3 ?k3 . }
  OPTIONAL { ?id cim:GovSteamFV3.mwbase ?mwbase . }
  OPTIONAL { ?id cim:GovSteamFV3.pmax ?pmax . }
  OPTIONAL { ?id cim:GovSteamFV3.pmin ?pmin . }
  OPTIONAL { ?id cim:GovSteamFV3.prmax ?prmax . }
  OPTIONAL { ?id cim:GovSteamFV3.t1 ?t1 . }
  OPTIONAL { ?id cim:GovSteamFV3.t2 ?t2 . }
  OPTIONAL { ?id cim:GovSteamFV3.t3 ?t3 . }
  OPTIONAL { ?id cim:GovSteamFV3.t4 ?t4 . }
  OPTIONAL { ?id cim:GovSteamFV3.t5 ?t5 . }
  OPTIONAL { ?id cim:GovSteamFV3.t6 ?t6 . }
  OPTIONAL { ?id cim:GovSteamFV3.ta ?ta . }
  OPTIONAL { ?id cim:GovSteamFV3.tb ?tb . }
  OPTIONAL { ?id cim:GovSteamFV3.tc ?tc . }
  OPTIONAL { ?id cim:GovSteamFV3.uc ?uc . }
  OPTIONAL { ?id cim:GovSteamFV3.uo ?uo . }
}
