#
# Copyright (c) 2026, RTE (http://www.rte-france.com)
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
PREFIX cim:  <%%CIM_NS%%>

PREFIX md:   <http://iec.ch/TC57/61970-552/ModelDescription/1#>

SELECT * WHERE {
  ?id rdf:type cim:GovSteamCC .
  OPTIONAL { ?id cim:TurbineGovernorDynamics.SynchronousMachineDynamics ?synchronousMachineId  . }
  OPTIONAL { ?id cim:GovSteamCC.mwbase ?mwbase . }
  OPTIONAL { ?id cim:GovSteamCC.rhp ?rhp . }
  OPTIONAL { ?id cim:GovSteamCC.t1hp ?t1hp . }
  OPTIONAL { ?id cim:GovSteamCC.t3hp ?t3hp . }
  OPTIONAL { ?id cim:GovSteamCC.t4hp ?t4hp . }
  OPTIONAL { ?id cim:GovSteamCC.t5hp ?t5hp . }
  OPTIONAL { ?id cim:GovSteamCC.fhp ?fhp . }
  OPTIONAL { ?id cim:GovSteamCC.dhp ?dhp . }
  OPTIONAL { ?id cim:GovSteamCC.pmaxhp ?pmaxhp . }
  OPTIONAL { ?id cim:GovSteamCC.rlp ?rlp . }
  OPTIONAL { ?id cim:GovSteamCC.t1lp ?t1lp . }
  OPTIONAL { ?id cim:GovSteamCC.t3lp ?t3lp . }
  OPTIONAL { ?id cim:GovSteamCC.t4lp ?t4lp . }
  OPTIONAL { ?id cim:GovSteamCC.t5lp ?t5lp . }
  OPTIONAL { ?id cim:GovSteamCC.flp ?flp . }
  OPTIONAL { ?id cim:GovSteamCC.dlp ?dlp . }
  OPTIONAL { ?id cim:GovSteamCC.pmaxlp ?pmaxlp . }
}
